### Show Users
GET http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzE1NjAyNDJ9.og4gFE8mDJWMRZ3XbbeswVHZNzO0sv-emqGvBllAr5E

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Tyra",
  "email": "tyra@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "zia@gmail.com",
  "password": "password"
}


